### ISSUE TITLE
Dots produced by build are not circular

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#11]
The dots produced by the build are more square than those produced by the Glyphs plugin, identical parameters:

![image](https://github.com/simoncozens/Dotter/assets/4226750/e5a335a7-e0a8-4f6b-82ca-238fed046ddd)

![image](https://github.com/simoncozens/Dotter/assets/4226750/ad5160af-9e40-4b0a-8fd0-6fa6f2f386b6)

**Comment by simoncozens** [comment]
I've done some digging on this, and the problem turns out to be.... fontmake! cu2qu has a default tolerance of 0.001 when converting cubics to quadratics:

![shape](https://github.com/simoncozens/Dotter/assets/106728/dc9efcbf-dee9-4490-a767-1e1ed403ede8)

Bumping this up an order of magnitude with `fontmake -e 0.00001`, we get:

![shape](https://github.com/simoncozens/Dotter/assets/106728/1f8613e8-8145-47c2-94d4-5488d89c1416)

(Trying another order of magnitude produces the wonderful
![shape](https://github.com/simoncozens/Dotter/assets/106728/2d123903-06b5-4a4b-bbca-d9df81e695fd)
)

**Comment by simoncozens** [comment]
To be fair, a 60 unit dot in a 2048 upem font is really pretty tiny, so I'm not sure we can really blame fontmake here.

**Comment by simoncozens** [comment]
We could do either, but changing the design of the dots seems more obviously correct.
