### ISSUE TITLE
Current Pendot Designer.glyphsFilter crashes

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#2]
With the latest changes the filter crashes on Glyphs startup and no longer activates, and generates the following error the next time Glyphs starts up:

![image](https://github.com/simoncozens/Dotter/assets/4226750/a8424123-e20b-45b2-8205-377491b76339)

**Comment by simoncozens** [comment]
I believe this is because, as dotting is now done using fontTools, you need the fontTools library installed in Glyphs (using the Plugin Manager). When we have something ready for "public" release, we'll put Dotter in the Glyphs Plugin Manager as well to make it easy to install, and that can declare a dependency on fontTools so that fontTools will be automatically installed with it.

For the time being I've made the plugin raise an alert message to tell the user to install fontTools if it is not found.

**Comment by simoncozens** [comment]
Unfortunately I can't reproduce it, it's working for me on the same Glyphs version. So if that doesn't work, the next debugging steps are:

1) Remove the plugin entirely and clone the repo again inside the Plugins directory.
2) Run Glyphs from the command line and look for the error message:

```
% /Applications/Glyphs\ 3.app/Contents/MacOS/Glyphs\ 3
2023-12-07 11:37:42.575 Glyphs 3[30660:757947] principalClass time: 0.853249  DotterController.glyphsReporter
2023-12-07 11:37:42.579 Glyphs 3[30660:757947] PendotDesigner has encountered a fatal error, and will now terminate.
2023-12-07 11:37:42.579 Glyphs 3[30660:757947] Traceback (most recent call last):

  File "/Users/simon/Library/Application Support/Glyphs 3/Plugins/Dotter/Pendot Designer.glyphsFilter/Contents/Resources/plugin.py", line 7, in <module>
...
```

**Comment by jvgaultney** [comment]
Deleting the existing repo clone and recloning got it working again - thanks!
