### ISSUE TITLE
Setting splitPaths = 1 in config data causes build to hang on exec

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#3]
If I try to run a project that has "splitPaths = 1" in the config data in fontinfo.plist the build process hangs on the first exec step. If I set it to "0" it works fine.

**Comment by simoncozens** [comment]
I can't reproduce this with font-pendot-latin; it builds fine. Can you isolate it to a font with a single glyph and send me that? (By email is OK if you don't want it public.) Flat out hangs are often caused by glyphsLib's `.segments` method not behaving; ensure you have glyphsLib >=6.6.0 and fontTools>=4.46.0.

**Comment by jvgaultney** [comment]
To reproduce pull changes to the font-pendot-latin repo, then replace config.yaml with renamed config.yaml.single, which will build from a separate PendotLSingle-Regular.glyphspackage master that contains only the letter E.

**Comment by jvgaultney** [comment]
For another example of this see failed build #12 vs successful build #13 of font-pendot-latin: https://github.com/silnrsi/font-pendot-latin/actions

**Comment by simoncozens** [comment]
Finally able to reproduce this and it is indeed yet another bug in `GSPath.segments`. I will find a minimal reproducer and raise an issue over at glyphsLib.

**Comment by simoncozens** [comment]
https://github.com/googlefonts/glyphsLib/pull/967 fixes it. You can add

```
glyphsLib @ git+https://github.com/googlefonts/gftools@segments-again
```

to requirements.txt if you're impatient...
